export const RichTextEditorConfig: any = {
    tools: {
		type: 'MultiRow',
        items: [
            'Undo',
            'Redo',
            '|',
            'Bold',
            'Italic',
            'Underline',
            'StrikeThrough',
            '|',
            'FontName',
            'FontSize',
            'FontColor',
            'BackgroundColor',
            '|',
            'SubScript',
            'SuperScript',
            '|',
            'LowerCase',
            'UpperCase',
            '|',
            'Formats',
            'Alignments',
            '|',
            'OrderedList',
            'UnorderedList',
            '|',
            'Indent',
            'Outdent',
            '|',
            'CreateLink',
            'Image',
            '|',
            'ClearFormat',
            'Print',
            'SourceCode',
            '|',
            'FullScreen',
        ],
    },
    size: {
        width: '40px',
		default: '13pt',
        items: [
            { text: '8', value: '8pt' },
            { text: '10', value: '10pt' },
            { text: '12', value: '12pt' },
            { text: '14', value: '14pt' },
            { text: '42', value: '42pt' },
        ],
    },
    family: {
        width: '60px',
		default: 'Arial',
        items: [
            { text: 'Arial', value: 'Arial,Helvetica,sans-serif' },
            { text: 'Impact', value: 'Impact,Charcoal,sans-serif' },

            { text: 'Segoe UI', value: 'Segoe UI' },
            { text: 'Courier New', value: 'Courier New,Courier,monospace' },
            { text: 'Georgia', value: 'Georgia,serif' },

            { text: 'Calibri Light', value: 'CalibriLight' },
        ],
    }
}
